import { API_URL } from 'constants'

export const POSTS__FAILED = 'POSTS__FAILED'
export const POSTS__IN_PROGRESS = 'POSTS__IN_PROGRESS'

export const POSTS__INIT_FORM = 'POSTS__INIT_FORM'

export const POSTS__FETCH_ITEM_RESPONSE = 'POSTS__FETCH_ITEM_RESPONSE'
export const POSTS__FETCH_ITEMS_URL = `${API_URL}/posts`
export const POSTS__FETCH_ITEMS_RESPONSE = 'POSTS__FETCH_ITEMS_RESPONSE'

export const POSTS__CREATE = 'POSTS__CREATE'
export const POSTS__UPDATE = 'POSTS__UPDATE'
export const POSTS__DELETE = 'POSTS__DELETE'
export const POSTS__UPDATE_ITEM_RESPONSE = 'POSTS__UPDATE_ITEM_RESPONSE'
export const POSTS__DELETE_ITEM_RESPONSE = 'POSTS__DELETE_ITEM_RESPONSE'

export const POSTS__FORM_FIELD_CHANGE = 'POSTS__FORM_FIELD_CHANGE'

export const POSTS__COLUMNS = ['id', 'title', 'body']
export const POSTS__COLUMNS_LABELS = {
  'actions' : 'Actions'
}

export const POSTS__SORT_FIELD = 'POSTS__SORT_FIELD'
export const POSTS__SORT_FIELDS = []

export const POSTS__FILTER_FIELD = 'POSTS__FILTER_FIELD'
export const POSTS__FILTER_FIELDS = []

export const POSTS__UPDATE_PAGINATION_LINK = 'POSTS__UPDATE_PAGINATION_LINK'
export const POSTS__PAGINATION_ITEMS = 'POSTS__PAGINATION_ITEMS'

export const POSTS__FORM_DEFAULT_STATE = {
  'key' : 'value'
}

export default {
  POSTS__FAILED,
  POSTS__IN_PROGRESS,
  POSTS__INIT_FORM,
  POSTS__FETCH_ITEM_RESPONSE,
  POSTS__FETCH_ITEMS_URL,
  POSTS__FETCH_ITEMS_RESPONSE,
  POSTS__CREATE,
  POSTS__UPDATE,
  POSTS__DELETE,
  POSTS__UPDATE_ITEM_RESPONSE,
  POSTS__DELETE_ITEM_RESPONSE,
  POSTS__FORM_FIELD_CHANGE,
  POSTS__COLUMNS,
  POSTS__COLUMNS_LABELS,
  POSTS__SORT_FIELD,
  POSTS__SORT_FIELDS,
  POSTS__FILTER_FIELD,
  POSTS__FILTER_FIELDS,
  POSTS__UPDATE_PAGINATION_LINK,
  POSTS__PAGINATION_ITEMS,
  POSTS__FORM_DEFAULT_STATE
}
